renderPath = "tmpl"
[[descriptor]]
    module = "ignore"
    srcName = "gitignore.tmpl"
    dstPath = "{{pathBackend}}/.gitignore"
[[descriptor]]
    module = "config"
    srcName = "config.toml.tmpl"
    dstPath = "{{pathBackend}}/config.toml"
[[descriptor]]
    module = "main"
    srcName = "main.go.tmpl"
    dstPath = "{{pathBackend}}/.gitignore"
# [[descriptor]]
#     module = "api"
#     srcName = "api.go.tmpl"
#     dstPath = "{{pathBackend}}/pkg/router/api/{{modelNameSnake}}.go"
# [[descriptor]]
#     module = "mysql"
#     srcName = "default_mysql.go.tmpl"
#     dstPath = "{{pathBackend}}/pkg/model/mysql/default.go"
#     once = true
[[descriptor]]
    module = "mysql"
    srcName = "mysql.go.tmpl"
    dstPath = "{{pathBackend}}/pkg/model/{{modelNameSnake}}.go"
[[descriptor]]
    module = "router"
    srcName = "router_api.go.tmpl"
    dstPath = "{{pathBackend}}/pkg/router/{{modelNameSnake}}.go"
[[descriptor]]
    module = "serveHttp"
    srcName = "serveHttp.go.tmpl"
    dstPath = "{{pathBackend}}/pkg/router/serveHttp.go"
[[descriptor]]
module = "main"
srcName = "main.go.tmpl"
dstPath = "{{pathBackend}}/main.go"
[[descriptor]]
module = "invoker"
srcName = "invoker.go.tmpl"
dstPath = "{{pathBackend}}/pkg/invoker/invoker.go"
[[descriptor]]
module = "makefile"
srcName = "makefile.tmpl"
dstPath = "{{pathBackend}}/Makefile"